### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by boronine** [memeplex/base16-prompt-toolkit#2]
Can you add a license? The README here recommends MIT: https://github.com/chriskempson/base16-templates-source

**Comment by memeplex** [comment]
Could you create a PR with the licence file? I don't really care which one.

**Comment by boronine** [comment]
Here it is https://github.com/memeplex/base16-prompt-toolkit/pull/3

**Comment by memeplex** [comment]
Thanks!
