### ISSUE TITLE
Not working with latest prompt-toolkit

### ISSUE THREAD

**Issue by sblask** [memeplex/base16-prompt-toolkit#6]
#4 hasn't actually been fixed as the base16 files haven't been updated. And even after changing it manually I still have this issue: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/766 and was wondering whether something can be changed here to make it work properly?

**Comment by memeplex** [comment]
Hi @sblask sadly I'm not maintaining this anymore, but feel free to fork it if you feel so.

**Comment by theova** [comment]
See #7 for a solution.
